name: Python workflow test sample 2
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # Step 2: Set up python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: requirements*.txt

#          pip install -r requirements.txt --extra-index-url https://${ado_token}@OUR_INETERNAL_ADO_PACKAGE 'REPO/_packaging/sepypi/pypi/simple/':
#             pip install -r requirements.txt --extra-index-url https://${ado_token}@OUR_INETERNAL_ADO_PACKAGE REPO/_packaging/sepypi/pypi/simple/  

      - name: Install dependencies f
        run: |
          pip --version
          pip install -r requirements.txt --extra-index-url https://${secrets.MY_KEY}@https://github.com/lmvysakh/vault_test/tree/main/source/mainfile/maincode/
